backend:
  name: github
  branch: main
  repo: specklesystems/speckle-docs
  site_domain: speckle-docs.netlify.app

publish_mode: editorial_workflow
media_folder: ".vuepress/public/uploads"
public_folder: ".vuepress/dist/"
collections:
  - name: "user" # Used in routes, e.g., /admin/collections/blog
    label: "User" # Used in the UI
    folder: "user" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "dev"
    label: "Dev"
    folder: "dev"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Title", name: "title", widget: "string" }
